version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # world-db is  world-db folder
  world-db:
     build: world-db/.
     command: --default-authentication-plugin=mysql_native_password
     restart: always
  

